/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.7 at Sun Sep 17 14:47:32 2017. */

#include "protocols.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t CanMessage_fields[7] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, CanMessage, DLC, DLC, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, CanMessage, RTR, DLC, 0),
    PB_FIELD(  3, UINT32  , REQUIRED, STATIC  , OTHER, CanMessage, IDE, RTR, 0),
    PB_FIELD(  4, UINT32  , REQUIRED, STATIC  , OTHER, CanMessage, ID, IDE, 0),
    PB_FIELD(  5, UINT32  , REQUIRED, STATIC  , OTHER, CanMessage, Data1, ID, 0),
    PB_FIELD(  6, UINT32  , REQUIRED, STATIC  , OTHER, CanMessage, Data2, Data1, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
